spring.application.name=metin-market-api
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/metin_market}
spring.datasource.username=${DATABASE_USERNAME:metin_market}
spring.datasource.password=${DATABASE_PASSWORD:metin_market}
spring.flyway.enabled=true
spring.sql.init.mode=never
app.scanner-token=${SCANNER_TOKEN}
server.error.include-message=always
